name: Windows

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: configure
        run: cmake -Stest -Bbuild

      - name: build
        run: cmake --build build --config Debug -j4
        
      - name: Zip Release

        uses: TheDoctor0/zip-release@0.6.2
        with:
          # Filename for archive
          filename: mac_debug.zip
          # Base path for archive files
          path: ${{ github.workspace }}/build/_deps/fmt-build/Debug/
          # Working directory before zipping
          directory: ${{ github.workspace }}/build/_deps/fmt-build/Debug/
          # List of excluded files / directories
          # exclusions: # optional, default is 
          # List of excluded files / directories with recursive wildcards (only applies on Windows with `zip` type)
          # recursive_exclusions: # optional, default is 
          # Tool to use for archiving
          type: zip

      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          # Artifact name
          name: arzip
          # Destination path
          path: ${{ github.workspace }}/build/_deps/fmt-build/Debug/mac_debug.zip
      - name: test
        run: |
          cd build
          ctest --build-config Debug
